name: Test Action
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo to use the action locally
        uses: actions/checkout@v4

      - name: Run my own container action
        id: my-action
        uses: ./
        with:
          who-to-get: '@wulfland'

      - name: Output the answer
        run: echo "The anwser is ${{ steps.my-action.outputs.answer }}"

      - name: Test the container
        if: ${{ steps.my-action.outputs.answer != 42 }}
        run: |
          echo "::error file=entrypoint.sh,line=4, title=Errpr in container::The answer was not expected"
          exit 1
